### ISSUE TITLE
Feature request: allow to refresh the cache and lacking info about individual activation of plugins

### ISSUE THREAD

**Issue by MarceloPedra** [WPStore/wpmu-plugin-stats#14]
Previous version of the plugin allowed to refresh the cache to have a real sense of what plugins are active and how. The latest version moved the activation info to the plugins list and as an admin I lost two very important things:

1) the ability to refresh the cache NOW to see what's activated and what's not. Now I have to wait or trust my feelings because the cache cannot be manually forced to be updated. May some "Refresh Active Plugins Cache" link be added as a system message to the plugins screen?

2) In the previous version, I was able to see a coloured background informing what plugins were globally activated, AND besides that, the plugin reported in what sites it has been individually activated before going global. This was useful when treating with old multisites where some plugins were individually activated AND after some time were globally activated. Now you have to deactivate a global plugin to see if it is also active in what sites. I think this can be improved by adding some color indicator  to the list of sites where the plugin is activated.

Hope you can take into consideration. Thanks!!

**Comment by MarceloPedra** [comment]
Please note that my work scenarios consist on lots of multisites systems, with hundreds of domains with a huge collection of HUNDREDS of plugins that are selectively activated in some sites. So, the more you can signal the status of plugin activations, the better work people like me will be able to do :)

**Comment by cfoellmann** [comment]
1. you can still manually refresh the data: https://github.com/wp-repository/wpmu-plugin-stats#when-is-the-stats-data-refreshed . But you don't have to if your network does not fall under the classification 'large_network'
2.1. _Network activated_ plugin rows are always blue in wp core
2.2 I am not sure what you mean by the second part of point 2. If a plugin is network activated later and was active on a site it is still loaded on these site. Please elaborate on that point.

**Comment by MarceloPedra** [comment]
1. Awesome. Sorry for not having read the docs. Anyway, what's the parameters you consider to define a network as large? # of installed plugins? # of sites? Consider that there are multisites with 100+ small sites with barely 10 active plugins.
2.1. Oh, yes, you're right... I must be color blind then.
2.2. Elaborating...

**Comment by cfoellmann** [comment]
_Large Network_ is defined in the `wp_is_large_network()` function https://github.com/WordPress/WordPress/blob/master/wp-includes/ms-functions.php#L2331-L2359

**Comment by MarceloPedra** [comment]
2.2. I was playing around and I think I can live with it. Never mind.

Good to know that limit starting on 10k sites/users. A shame that 1k is still not being considered a big enough network :)

Very thanks for the clarifications

**Comment by cfoellmann** [comment]
Thanks for the feedback anyway.

I am planning to add a refresh link in the next release and will keep this issue open as a reminder.

**Comment by MarceloPedra** [comment]
Great, I will look forward to test it. Thanks.

**Comment by cfoellmann** [comment]
this is old and I have no illusion that you @MarceloPedra are still using the plugin.
you must have seen that you can use the filter ``wp_is_large_network` to just make your network be recognized as large. BUT that might have other side effects.
